module.exports = (sequelize, Sequelize) => {
  return sequelize.define("battle", {
    name: Sequelize.TEXT,
    year: Sequelize.INTEGER,
    battle_number: Sequelize.INTEGER,
    attacker_king: Sequelize.TEXT,
    defender_king: Sequelize.TEXT,
    attacker_1: Sequelize.TEXT,
    attacker_2: Sequelize.TEXT,
    attacker_3: Sequelize.TEXT,
    attacker_4: Sequelize.TEXT,
    defender_1: Sequelize.TEXT,
    defender_2: Sequelize.TEXT,
    defender_3: Sequelize.TEXT,
    defender_4: Sequelize.TEXT,
    attacker_outcome: Sequelize.TEXT,
    battle_type: Sequelize.TEXT,
    major_death: Sequelize.INTEGER,
    major_capture: Sequelize.INTEGER,
    attacker_size: Sequelize.TEXT,
    defender_size: Sequelize.TEXT,
    attacker_commander: Sequelize.TEXT,
    defender_commander: Sequelize.TEXT,
    summer: Sequelize.TEXT,
    location: Sequelize.TEXT,
    region: Sequelize.TEXT,
    note: Sequelize.TEXT
  });
};

//   name varchar(52) DEFAULT NULL,
//   year int DEFAULT NULL,
//   battle_number int DEFAULT NULL,
//   attacker_king varchar(24) DEFAULT NULL,
//   defender_king varchar(24) DEFAULT NULL,
//   attacker_1 varchar(27) DEFAULT NULL,
//   attacker_2 varchar(9) DEFAULT NULL,
//   attacker_3 varchar(7) DEFAULT NULL,
//   attacker_4 varchar(6) DEFAULT NULL,
//   defender_1 varchar(16) DEFAULT NULL,
//   defender_2 varchar(9) DEFAULT NULL,
//   defender_3 varchar(10) DEFAULT NULL,
//   defender_4 varchar(10) DEFAULT NULL,
//   attacker_outcome varchar(4) DEFAULT NULL,
//   battle_type varchar(14) DEFAULT NULL,
//   major_death int DEFAULT NULL,
//   major_capture int DEFAULT NULL,
//   attacker_size varchar(6) DEFAULT NULL,
//   defender_size varchar(5) DEFAULT NULL,
//   attacker_commander varchar(95) DEFAULT NULL,
//   defender_commander varchar(109) DEFAULT NULL,
//   summer varchar(1) DEFAULT NULL,
//   location varchar(36) DEFAULT NULL,
//   region varchar(15) DEFAULT NULL,
//   note varchar(257) DEFAULT NULL
